-- phpMyAdmin SQL Dump
-- version 3.4.10.1
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le : Mer 04 Juin 2014 à 15:57
-- Version du serveur: 5.5.20
-- Version de PHP: 5.3.10

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `tnjob`
--

-- --------------------------------------------------------

--
-- Structure de la table `job`
--

CREATE TABLE IF NOT EXISTS `job` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` int(11) DEFAULT NULL,
  `user` int(11) DEFAULT NULL,
  `type` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `position` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `location` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `description` longtext COLLATE utf8_unicode_ci,
  `how_to_apply` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `token` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `is_public` tinyint(1) DEFAULT NULL,
  `is_activated` tinyint(1) DEFAULT NULL,
  `email` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `expires_at` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `IDX_FBD8E0F864C19C1` (`category`),
  KEY `IDX_FBD8E0F88D93D649` (`user`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=40 ;

--
-- Contenu de la table `job`
--

INSERT INTO `job` (`id`, `category`, `user`, `type`, `position`, `location`, `description`, `how_to_apply`, `token`, `is_public`, `is_activated`, `email`, `expires_at`, `created_at`, `updated_at`) VALUES
(1, 1, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(2, 1, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(3, 1, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(4, 1, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(5, 1, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(6, 2, 2, 'Plein temps', 'Développeur java', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(7, 2, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(8, 2, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(9, 2, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(10, 2, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(11, 4, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(12, 4, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(13, 4, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(14, 4, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(15, 4, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(16, 4, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(17, 1, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(18, 2, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(19, 2, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(20, 4, 2, 'Plein temps', 'Développeur web', 'Tunis Tunisie', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', 'azerty', 'tctuggvigbiuhbii', 1, 1, 'email@email.com', '2016-06-30 00:00:00', '2014-03-06 00:00:00', '2014-03-06 00:00:00'),
(21, 1, 4, 'part-time', 'TEST', 'TEST', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', NULL, NULL, NULL, NULL, 'tftggyyui@test.com', NULL, NULL, NULL),
(22, 1, 4, 'part-time', 'TEST', 'TEST', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', NULL, NULL, NULL, NULL, 'tftggyyui@test.com', NULL, NULL, NULL),
(23, 1, 4, 'part-time', 'TEST', 'TEST', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', NULL, NULL, NULL, NULL, 'tftggyyui@test.com', NULL, NULL, NULL),
(24, 1, 4, 'part-time', 'TEST', 'TEST', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', NULL, NULL, NULL, NULL, 'tftggyyui@test.com', NULL, NULL, NULL),
(25, 3, 4, 'part-time', 'TEST', 'TEST', 'Objectif : Développement d''applications web robustes basées sur Ruby on Rails\r\nCompétences requises (développeur web ) : \r\n -  Expérience significative dans le développement Web, avec Ruby on Rails (2ans).\r\n -  Expérience significative avec les technologies de l''internet : HTML5, CSS3 (SASS), Javascript, Ajax)\r\n -  Base de données Mysql, MongoDB\r\n -  Connaissance architecture MVC, REST\r\n -  Utilisation de GIT\r\n -  Langue FR/EN\r\n \r\nBonus : \r\n -  Utilisation framework Css type Bootstrap.\r\n -  Expérience sous Angular.js\r\n -  Connaissance des méthodes agiles (SCRUM)\r\n \r\nRéférences : \r\n  -  Projets déjà développés,\r\n  -  Profil Github, Stackoverflow', NULL, 'a40917f2e90f24027d5848027d450137', NULL, 1, 'tftggyyui@test.com', NULL, NULL, NULL),
(26, 1, 2, 'part-time', 'jjjj', 'jjhhjh', 'khhkkhkk', NULL, 'fcd013968f5a301e05246ee2ae37a3f8', NULL, 1, 'hkhkhk@jcj.hf', NULL, NULL, NULL),
(27, 1, 2, 'part-time', 'jdjsjd', 'kdsjsk@ldl.kf', 'k', NULL, '4bc35f9f2dccd70a7886cf203be46709', NULL, 1, 'kdsjsk@ldl.kf', NULL, NULL, NULL),
(28, 1, 2, 'part-time', 'vlkdne', 'lekf@epfljz', 'nhcsjb', NULL, '67fb20b96de45e60efadf524435e4a60', NULL, 1, 'lekf@epfljz', NULL, NULL, NULL),
(29, 1, 2, 'part-time', 'jjjjjjjjjjjjjjjjjjjjjjjjjj', 'hhhhhhhhhhhhhhhhhhhhhhhhhh', 'ggmlfkhlkflkhmllkhmlkmhkdlkhhl\r\nhgkhlgkhlgkh^gkhlghkglh^\r\nhgklkhg\r\nkhfgfpkpghkgfj', NULL, '8c9a9af6a42fc423bca771d2db7ec9b0', NULL, 1, 'hhhhhhhhhhhhhhh@hhhhh.hhhh', NULL, NULL, NULL),
(30, 1, 1, 'frfrfffff', 'ffffffff', 'fffffffffff', 'fffffffffffffffffff', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(31, 1, 1, 'aaa', 'aaaa', 'aaaa', 'aaaaa', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(32, 1, 2, 'kjkjkjkjk', 'llllllllll', 'lflflf', 'kddldld', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(33, 1, 1, 'fffffffgggggg', 'fffffffgggggg', 'ffffffffggggggg', 'ffffffggggggggg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(34, 1, 1, 'ggggg', 'ggggg', 'gggggggg', 'gggggggggg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(35, 1, 1, 'kkkkkk', 'kkkkk', 'kkkk', 'kkkkkkk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(36, 1, 1, 'kkkkkk', 'kkkkk', 'kkkk', 'kkkkkkk', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(37, 1, 1, 'dddddddd', 'ffffff', 'fffff', 'fffffffffff', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(38, 1, 1, 'mmmmm', 'mmmmmm', 'mmmmmm', 'mmmmm', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(39, 1, 1, 'dev', 'souse', 'souse', 'android', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

--
-- Contraintes pour les tables exportées
--

--
-- Contraintes pour la table `job`
--
ALTER TABLE `job`
  ADD CONSTRAINT `FK_FBD8E0F864C19C1` FOREIGN KEY (`category`) REFERENCES `category` (`id`),
  ADD CONSTRAINT `FK_FBD8E0F88D93D649` FOREIGN KEY (`user`) REFERENCES `user` (`id`);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
